name: branch

on:
  push:
    branches-ignore: [main, gh-pages]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: wtnb75/actions/python@d46e83a56abd145ef1af4a26bc9837ecd8ca4598 # v1.0.7
    - uses: wtnb75/actions/ruff@d46e83a56abd145ef1af4a26bc9837ecd8ca4598 # v1.0.7
    - uses: wtnb75/actions/pytest@d46e83a56abd145ef1af4a26bc9837ecd8ca4598 # v1.0.7
    - uses: wtnb75/actions/wheel@d46e83a56abd145ef1af4a26bc9837ecd8ca4598 # v1.0.7
    - id: pdoc
      uses: wtnb75/actions/pdoc@d46e83a56abd145ef1af4a26bc9837ecd8ca4598 # v1.0.7
      with:
        output-dir: docs
        module: selenible
        other-options: --docformat google
    - uses: wtnb75/actions/merge-pages@d46e83a56abd145ef1af4a26bc9837ecd8ca4598 # v1.0.7
      with:
        dirs: "cover docs"
        #pydist: dist
