name: branch

on:
  push:
    branches-ignore: [main, gh-pages]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: wtnb75/actions/python@v1
    - uses: wtnb75/actions/ruff@v1
    - uses: wtnb75/actions/pytest@v1
    - uses: wtnb75/actions/wheel@v1
    - id: pdoc
      uses: wtnb75/actions/pdoc@v1
      with:
        output-dir: docs
        module: selenible
        other-options: --docformat google
    - uses: wtnb75/actions/merge-pages@v1
      with:
        dirs: "cover docs"
        #pydist: dist
