name: release to pypi

on:
  push:
    tags:
    - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: setup python 3.8
      uses: actions/setup-python@v1
      with:
        python-version: 3.8
    - name: get pip cache
      id: pip-cache
      run: |
        python -c "from pip._internal.locations import USER_CACHE_DIR; print('::set-output name=dir::' + USER_CACHE_DIR)"
    - name: cache
      uses: actions/cache@v1
      with:
        path: ${{ steps.pip-cache.outputs.dir }}
        key: ${{ runner.os }}-pip-${{ hashfiles('**/requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-
    - name: Install dependencies
      run: pip install -r requirements.txt -r requirements-dev.txt
    - name: versioning
      run: "echo \"VERSION = '${GITHUB_REF##*/v}'\" > selenible/version.py"
    - name: build wheel
      run: python setup.py bdist_wheel
    - name: check
      run: twine check dist/*.whl
    - name: deploy to pypi
      run: twine upload dist/*.whl
      env:
        TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}
        TWINE_REPOSITORY_URL: ${{ secrets.TWINE_REPOSITORY_URL }}
        TWINE_NON_INTERACTIVE: "1"
