name: update-deps

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  update-deps:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - uses: wtnb75/actions/python@v1
    - uses: wtnb75/actions/pyupdate@v1
      with:
        test-args: "-xs"
